server:
  port: 8080

# FIXME: only development
#debug: true
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

spring:
  # resources & source hot reload
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker: # FIXME: only development
    cache: false
  # coloring console
  output:
    ansi:
      enabled: always
  # disable thymeleaf cache
  thymeleaf:
    cache: false  # FIXME: only development
    prefix: classpath:templates/
  # spring.datasource to db
  datasource:
    url: jdbc:mysql://localhost/test_boarddb?serverTimezone=UTC
    username: admin
    password: dkdlwkr
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mapper/*Mapper.xml

org.gradle.warning.mode: all